---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.7
      gemfile: gemfiles/4.2.gemfile

notifications:
  email: false
